name: Inferno Container
on:
  push:
  repository_dispatch:
    types: [changed]
    branch: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build image
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/inferno-os:latest .
